frontend:
  - changed-files:
    - any-glob-to-any-file: "client/**"

backend:
  - changed-files:
    - any-glob-to-any-file: "server/**"

"ci/cd":
  - changed-files:
    - any-glob-to-any-file: ".github/**"

docs:
  - changed-files:
    - any-glob-to-any-file: "**/*.md"

feature:
  - head-branch: ["^feat/"]

fix:
  - head-branch: ["^fix/"]

chore:
  - head-branch: ["^chore/"]
