name: PR Metrics

on:
  pull_request:

jobs:
  pr-metrics:
    name: PR Metrics
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: microsoft/PR-Metrics@v1.7.15
        continue-on-error: true
        env:
          PR_METRICS_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          base-size: 150
          file-matching-patterns: |
            **/*
            !**/package-lock.json
          code-file-extensions: |
            js
            jsx
            ts
            tsx
            css
